/**
 * Catálogo de ejercicios predefinido con imágenes locales
 * Las imágenes están en la carpeta /ejercicios en la raíz del proyecto
 * Todas las imágenes tienen fondo blanco para mejor presentación
 */

export interface ExerciseCatalogItem {
  id: string;
  name: string;
  muscle_group: string;
  equipment: string;
  image_url: string; // Ruta local a las imágenes
  target_muscles?: string[];
  description?: string; // Descripción detallada del ejercicio
}

export const EXERCISE_CATALOG: ExerciseCatalogItem[] = [
  // ===== PECHO =====
  {
    id: "bench_press_barbell",
    name: "Bench Press (Barra)",
    muscle_group: "Pecho",
    equipment: "Barra",
    image_url: "../../ejercicios/Bench Press - fondo blanco.png",
    target_muscles: ["Pecho", "Tríceps", "Hombros"],
    description: "Ejercicio fundamental para desarrollar el pecho. Acuéstate en banco plano, baja la barra controladamente hasta el pecho y empuja explosivamente. Trabaja principalmente pectoral mayor, tríceps y deltoides anterior. Mantén escápulas retraídas y pies firmes en el suelo.",
  },
  {
    id: "incline_bench_press",
    name: "Incline Bench Press",
    muscle_group: "Pecho",
    equipment: "Barra",
    image_url: "../../ejercicios/Bench Press - fondo blanco.png",
    target_muscles: ["Pecho Superior", "Hombros"],
    description: "Variante inclinada del bench press (30-45°) que enfatiza el pectoral superior. Ideal para desarrollar la parte clavicular del pecho. Mantén la misma técnica que el bench press plano pero con mayor activación de deltoides anteriores.",
  },
  {
    id: "dumbbell_bench_press",
    name: "Dumbbell Bench Press",
    muscle_group: "Pecho",
    equipment: "Mancuernas",
    image_url: "../../ejercicios/Dumbbell_Bench_Press - fondo blanco.png",
    target_muscles: ["Pecho", "Tríceps"],
    description: "Press con mancuernas que permite mayor rango de movimiento y activación independiente de cada lado. Mejora la estabilidad y corrige desbalances. Baja las mancuernas hasta sentir estiramiento en el pecho, sin bajar hombros.",
  },
  {
    id: "push_ups",
    name: "Push-ups",
    muscle_group: "Pecho",
    equipment: "Peso Corporal",
    image_url: "../../ejercicios/white_Push-ups.png",
    target_muscles: ["Pecho", "Tríceps", "Hombros"],
    description: "Ejercicio clásico de peso corporal para pecho y tríceps. Mantén cuerpo recto, baja controladamente hasta que el pecho casi toque el suelo. Trabaja core, estabilidad y fuerza funcional. Variantes: elevadas, declinadas, diamante.",
  },
  {
    id: "cable_fly",
    name: "Cable Fly",
    muscle_group: "Pecho",
    equipment: "Cables",
    image_url: "../../ejercicios/Cable Fly - fondo blanco.png",
    target_muscles: ["Pecho"],
    description: "Ejercicio de aislamiento para pecho con tensión constante por cables. Abre brazos en arco amplio manteniendo ligera flexión en codos, luego junta las manos al centro. Excelente para congestión y definición muscular.",
  },

  // ===== ESPALDA =====
  {
    id: "pull_ups",
    name: "Pull-ups",
    muscle_group: "Espalda",
    equipment: "Barra",
    image_url: "../../ejercicios/white_Pull-ups.png",
    target_muscles: ["Espalda Dorsal", "Bíceps"],
    description: "Rey de los ejercicios de espalda. Cuelga de la barra con agarre prono, tira el cuerpo hacia arriba hasta que la barbilla supere la barra. Desarrolla dorsales, bíceps y fuerza de agarre. Si no puedes hacer dominadas, usa banda elástica o máquina asistida.",
  },
  {
    id: "lat_pulldown",
    name: "Lat Pulldown",
    muscle_group: "Espalda",
    equipment: "Máquina",
    image_url: "../../ejercicios/Lat_Pulldown.png",
    target_muscles: ["Espalda Dorsal", "Bíceps"],
    description: "Alternativa a las dominadas en máquina. Jala la barra hacia el pecho manteniendo espalda ligeramente arqueada y pecho hacia afuera. Trabaja dorsal ancho principalmente. Evita balancear el torso o usar impulso.",
  },
  {
    id: "barbell_row",
    name: "Barbell Row",
    muscle_group: "Espalda",
    equipment: "Barra",
    image_url: "../../ejercicios/Barbell Row - fondo blanco.png",
    target_muscles: ["Espalda", "Bíceps"],
    description: "Ejercicio compuesto para grosor de espalda. Inclínate 45° con espalda recta, jala la barra hacia el abdomen bajo. Trabaja dorsales, trapecios medios, romboides y erectores espinales. Mantén core activado para proteger zona lumbar.",
  },
  {
    id: "dumbbell_row",
    name: "Dumbbell Row",
    muscle_group: "Espalda",
    equipment: "Mancuernas",
    image_url: "../../ejercicios/Dumbbell_Row - fondo blanco.png",
    target_muscles: ["Espalda", "Bíceps"],
    description: "Remo unilateral que permite mayor rango de movimiento y corrige desbalances. Apoya rodilla y mano en banco, jala mancuerna hacia cadera. Enfoca en contraer dorsales y llevar codo hacia atrás, no solo subir el peso.",
  },
  {
    id: "face_pull",
    name: "Face Pull",
    muscle_group: "Espalda",
    equipment: "Cables",
    image_url: "../../ejercicios/Face_Pull - fondo blanco.png",
    target_muscles: ["Espalda Posterior", "Hombros"],
    description: "Esencial para salud de hombros y postura. Jala cuerda hacia la cara separando las manos al final. Trabaja deltoides posterior, trapecio medio y romboides. Excelente para contrarrestar el trabajo de pecho y prevenir lesiones.",
  },

  // ===== HOMBROS =====
  {
    id: "overhead_press",
    name: "Overhead Press",
    muscle_group: "Hombros",
    equipment: "Barra",
    image_url: "../../ejercicios/Overhead_Press_white_background.png",
    target_muscles: ["Hombros", "Tríceps"],
    description: "Press militar, ejercicio básico para hombros. Empuja la barra desde altura de hombros hasta extensión completa sobre la cabeza. Desarrolla deltoides, tríceps y core. Mantén abdomen contraído y evita arquear excesivamente la espalda baja.",
  },
  {
    id: "dumbbell_shoulder_press",
    name: "Dumbbell Shoulder Press",
    muscle_group: "Hombros",
    equipment: "Mancuernas",
    image_url: "../../ejercicios/Dumbbell_Shoulder_Press - fondo blanco.png",
    target_muscles: ["Hombros", "Tríceps"],
    description: "Press con mancuernas sentado o de pie. Permite mayor rango de movimiento natural que la barra. Empuja mancuernas desde hombros hasta arriba sin chocarlas. Trabaja deltoides anterior y medio principalmente, con estabilización superior.",
  },
  {
    id: "lateral_raise",
    name: "Lateral Raise",
    muscle_group: "Hombros",
    equipment: "Mancuernas",
    image_url: "../../ejercicios/frontheben-kurzhanteln-800x448 - fondo blanco.png",
    target_muscles: ["Hombros Laterales"],
    description: "Aislamiento para deltoides lateral (cabeza media del hombro). Eleva los brazos lateralmente hasta altura de hombros con ligera flexión de codos. No uses impulso ni levantes demasiado peso. Clave para hombros anchos y definidos.",
  },
  {
    id: "front_raise",
    name: "Front Raise",
    muscle_group: "Hombros",
    equipment: "Mancuernas",
    image_url: "../../ejercicios/Front_Raise - fondo blanco.png",
    target_muscles: ["Hombros Anteriores"],
    description: "Aislamiento para deltoides anterior. Eleva mancuernas al frente hasta altura de ojos con brazos extendidos. Ya se trabaja bastante en presses, úsalo como complemento. Control descendente es crucial para evitar lesiones.",
  },
  {
    id: "reverse_fly",
    name: "Reverse Fly",
    muscle_group: "Hombros",
    equipment: "Mancuernas",
    image_url: "../../ejercicios/white_Reverse_Fly.png",
    target_muscles: ["Espalda Posterior", "Hombros"],
    description: "Apertura invertida para deltoides posterior. Inclínate hacia adelante, abre brazos en arco lateral apretando omoplatos. Esencial para balance muscular, postura y salud de hombros. Usa peso moderado con control total.",
  },

  // ===== BRAZOS (BÍCEPS) =====
  {
    id: "barbell_curl",
    name: "Barbell Curl",
    muscle_group: "Brazos",
    equipment: "Barra",
    image_url: "../../ejercicios/Barbell Curl - fondo blanco.png",
    target_muscles: ["Bíceps"],
    description: "Curl clásico con barra para bíceps. Mantente erguido, codos pegados al torso, flexiona antebrazos sin balancear el cuerpo. Trabaja ambas cabezas del bíceps. Controla la fase excéntrica (bajada) para máximo crecimiento.",
  },
  {
    id: "dumbbell_curl",
    name: "Dumbbell Curl",
    muscle_group: "Brazos",
    equipment: "Mancuernas",
    image_url: "../../ejercicios/Barbell Curl - fondo blanco.png",
    target_muscles: ["Bíceps"],
    description: "Curl con mancuernas que permite rotación natural del antebrazo (supinación). Alterna o simultáneo. Trabaja bíceps con mayor activación del braquial. Rota las muñecas hacia arriba en la parte alta del movimiento.",
  },
  {
    id: "hammer_curl",
    name: "Hammer Curl",
    muscle_group: "Brazos",
    equipment: "Mancuernas",
    image_url: "../../ejercicios/Hammer_Curl - fondo blanco.png",
    target_muscles: ["Bíceps"],
    description: "Curl con agarre neutro (palmas enfrentadas). Enfatiza braquial y braquiorradial además de bíceps. Excelente para grosor del brazo y fuerza de agarre. Permite usar más peso que curl tradicional.",
  },
  {
    id: "cable_curl",
    name: "Cable Curl",
    muscle_group: "Brazos",
    equipment: "Cables",
    image_url: "../../ejercicios/Cable Curl - fondo blanco.png",
    target_muscles: ["Bíceps"],
    description: "Curl en polea con tensión constante durante todo el movimiento. Mayor tiempo bajo tensión que con peso libre. Ideal para finales de rutina o cambio de estímulo. Mantén codos fijos y aprieta en la contracción.",
  },

  // ===== BRAZOS (TRÍCEPS) =====
  {
    id: "close_grip_press",
    name: "Close Grip Bench Press",
    muscle_group: "Brazos",
    equipment: "Barra",
    image_url: "../../ejercicios/Close_Grip_Bench_Press - fondo blanco.png",
    target_muscles: ["Tríceps", "Pecho"],
    description: "Press con agarre cerrado (ancho de hombros) que enfatiza tríceps. Baja la barra al pecho bajo manteniendo codos cerca del torso. Ejercicio compuesto excelente para masa de tríceps. Permite cargar más peso que ejercicios de aislamiento.",
  },
  {
    id: "tricep_dips",
    name: "Tricep Dips",
    muscle_group: "Brazos",
    equipment: "Peso Corporal",
    image_url: "../../ejercicios/white_Tricep_Dips.png",
    target_muscles: ["Tríceps"],
    description: "Fondos en paralelas para tríceps. Baja controladamente hasta 90° en codos, empuja hacia arriba. Mantén torso vertical para enfatizar tríceps. Ejercicio muy efectivo de peso corporal, agrega peso cuando domines tu masa corporal.",
  },
  {
    id: "tricep_pushdown",
    name: "Tricep Pushdown",
    muscle_group: "Brazos",
    equipment: "Cables",
    image_url: "../../ejercicios/white_Tricep_Pushdown.png",
    target_muscles: ["Tríceps"],
    description: "Extensión de tríceps en polea alta. Mantén codos fijos a los lados, empuja hacia abajo hasta extensión completa. Trabaja principalmente cabeza lateral del tríceps. Perfecto para aislamiento y congestión muscular.",
  },
  {
    id: "dumbbell_tricep_extension",
    name: "Dumbbell Tricep Extension",
    muscle_group: "Brazos",
    equipment: "Mancuernas",
    image_url: "../../ejercicios/Dumbbell_Tricep_Extension - fondo blanco.png",
    target_muscles: ["Tríceps"],
    description: "Extensión de tríceps sobre cabeza con mancuerna. Sube la mancuerna sobre la cabeza, baja detrás de la cabeza doblando solo codos. Trabaja cabeza larga del tríceps. Mantén codos apuntando arriba y core activado.",
  },

  // ===== PIERNAS (CUÁDRICEPS) =====
  {
    id: "barbell_squat",
    name: "Barbell Squat",
    muscle_group: "Piernas",
    equipment: "Barra",
    image_url: "../../ejercicios/Barbell Squat - fondo blanco.png",
    target_muscles: ["Cuádriceps", "Glúteos"],
    description: "Rey de los ejercicios de piernas. Barra en trapecios, baja controladamente hasta muslos paralelos al suelo o más. Trabaja cuádriceps, glúteos, core y espalda baja. Mantén rodillas alineadas con pies, espalda neutra y pecho arriba.",
  },
  {
    id: "leg_press",
    name: "Leg Press",
    muscle_group: "Piernas",
    equipment: "Máquina",
    image_url: "../../ejercicios/Leg_Press_white_background.png",
    target_muscles: ["Cuádriceps", "Glúteos"],
    description: "Prensa de piernas en máquina. Empuja la plataforma con pies en posición media-alta. Trabaja cuádriceps y glúteos sin carga en la espalda. Baja hasta 90° (rodillas cerca del pecho), evita despegar glúteos del respaldo.",
  },
  {
    id: "leg_extension",
    name: "Leg Extension",
    muscle_group: "Piernas",
    equipment: "Máquina",
    image_url: "../../ejercicios/white_Leg_Extension.png",
    target_muscles: ["Cuádriceps"],
    description: "Aislamiento puro de cuádriceps. Extiende piernas contra la resistencia hasta extensión completa, aprieta cuádriceps arriba. Baja controladamente. Excelente para pre-fatiga o finalizador de piernas. No sobrecargues si tienes problemas de rodilla.",
  },
  {
    id: "dumbbell_goblet_squat",
    name: "Goblet Squat",
    muscle_group: "Piernas",
    equipment: "Mancuernas",
    image_url: "../../ejercicios/Goblet_Squat - fondo blanco.png",
    target_muscles: ["Cuádriceps", "Glúteos"],
    description: "Sentadilla sosteniendo mancuerna o kettlebell al pecho. Excelente para principiantes o movilidad. La carga frontal ayuda a mantener torso erguido. Baja profundo manteniendo codos entre rodillas. Gran ejercicio para técnica de sentadilla.",
  },
  {
    id: "smith_machine_squat",
    name: "Smith Machine Squat",
    muscle_group: "Piernas",
    equipment: "Smith Machine",
    image_url: "../../ejercicios/Smith_Machine_Squat_white_background.png",
    target_muscles: ["Cuádriceps"],
    description: "Sentadilla en máquina Smith con trayectoria fija. Permite aislar piernas sin preocuparse por equilibrio. Puedes colocar pies más adelante para mayor énfasis en cuádriceps. Buena opción para entrenar seguro al fallo.",
  },

  // ===== PIERNAS (ISQUIOTIBIALES) =====
  {
    id: "leg_curl",
    name: "Leg Curl",
    muscle_group: "Piernas",
    equipment: "Máquina",
    image_url: "../../ejercicios/white_Leg_Curl.png",
    target_muscles: ["Isquiotibiales"],
    description: "Aislamiento de isquiotibiales (femoral). Acostado o sentado, flexiona piernas llevando talones hacia glúteos. Trabaja parte posterior del muslo. Aprieta en la contracción y controla la bajada. Esencial para balance muscular de piernas.",
  },
  {
    id: "barbell_deadlift",
    name: "Barbell Deadlift",
    muscle_group: "Piernas",
    equipment: "Barra",
    image_url: "../../ejercicios/Barbell Deadlift - fondo blanco.png",
    target_muscles: ["Isquiotibiales", "Espalda", "Glúteos"],
    description: "Peso muerto, uno de los mejores ejercicios compuestos. Levanta la barra del suelo hasta estar erguido, luego baja controladamente. Trabaja cadena posterior completa: isquios, glúteos, espalda baja, trapecios. Técnica es crítica para evitar lesiones.",
  },
  {
    id: "romanian_deadlift",
    name: "Romanian Deadlift",
    muscle_group: "Piernas",
    equipment: "Barra",
    image_url: "../../ejercicios/white_Romanian_Deadlift.png",
    target_muscles: ["Isquiotibiales", "Glúteos"],
    description: "Variante de peso muerto que enfatiza isquiotibiales y glúteos. Baja la barra deslizándola por las piernas con rodillas ligeramente flexionadas, sintiendo estiramiento en femorales. No toques el suelo. Excelente para desarrollo de cadena posterior.",
  },
  {
    id: "dumbbell_deadlift",
    name: "Dumbbell Deadlift",
    muscle_group: "Piernas",
    equipment: "Mancuernas",
    image_url: "../../ejercicios/Dumbbell_Deadlift - fondo blanco.png",
    target_muscles: ["Isquiotibiales", "Espalda"],
    description: "Peso muerto con mancuernas. Permite mayor rango natural de movimiento y es más amigable para principiantes. Trabaja isquios, glúteos y espalda baja. Mantén mancuernas cerca del cuerpo y espalda neutra durante todo el movimiento.",
  },

  // ===== GLÚTEOS =====
  {
    id: "hip_thrust",
    name: "Hip Thrust",
    muscle_group: "Glúteos",
    equipment: "Barra",
    image_url: "../../ejercicios/Hip_Thrust_white_background.png",
    target_muscles: ["Glúteos"],
    description: "El mejor ejercicio para glúteos. Apoya espalda en banco, barra sobre cadera, empuja con glúteos hasta extensión completa de cadera. Aprieta glúteos arriba por 1 segundo. Permite cargar mucho peso de forma segura. Fundamental para desarrollo de glúteos.",
  },
  {
    id: "hack_squat",
    name: "Hack Squat",
    muscle_group: "Glúteos",
    equipment: "Smith Machine",
    image_url: "../../ejercicios/Hack_Squat - fondo blanco.png",
    target_muscles: ["Glúteos", "Cuádriceps"],
    description: "Sentadilla en máquina hack con ángulo de 45°. Pies en posición alta énfasis glúteos, posición baja más cuádriceps. Permite entrenar piernas pesado sin estrés en espalda baja. Baja profundo para máxima activación.",
  },
  {
    id: "bulgarian_split_squat",
    name: "Bulgarian Split Squat",
    muscle_group: "Glúteos",
    equipment: "Peso Corporal",
    image_url: "../../ejercicios/Bulgarian Split Squat - fondo blanco.png",
    target_muscles: ["Glúteos", "Cuádriceps"],
    description: "Sentadilla unilateral con pie trasero elevado. Trabaja glúteos, cuádriceps y equilibrio. Baja hasta que rodilla trasera casi toque el suelo. Corrige desbalances entre piernas. Agrega mancuernas cuando domines el peso corporal.",
  },

  // ===== CORE/ABS =====
  {
    id: "barbell_crunch",
    name: "Barbell Crunch",
    muscle_group: "Core",
    equipment: "Barra",
    image_url: "../../ejercicios/Barbell Crunch - fondo blanco.png",
    target_muscles: ["Abdominales"],
    description: "Crunch sosteniendo barra sobre el pecho. Permite agregar carga progresiva a abdominales. Flexiona la columna llevan los hombros hacia la pelvis. Trabaja recto abdominal. Exhala al subir, contraé abdomen.",
  },
  {
    id: "ab_crunch",
    name: "Crunch",
    muscle_group: "Core",
    equipment: "Máquina",
    image_url: "../../ejercicios/Crunch - fondo blanco.png",
    target_muscles: ["Abdominales"],
    description: "Crunch en máquina con resistencia ajustable. Flexiona el tronco hacia adelante contra la resistencia. Trabaja principalmente recto abdominal. Movimiento controlado, evita usar impulso con brazos o cuello.",
  },
  {
    id: "decline_situps",
    name: "Decline Sit-ups",
    muscle_group: "Core",
    equipment: "Peso Corporal",
    image_url: "../../ejercicios/Decline_Sit-ups - fondo blanco.png",
    target_muscles: ["Abdominales"],
    description: "Abdominales en banco declinado. Mayor rango de movimiento y dificultad que crunch normal. Sube el torso completo hasta posición vertical. Trabaja recto abdominal y flexores de cadera. Sostiene peso en pecho para mayor intensidad.",
  },
  {
    id: "cable_crunch",
    name: "Cable Crunch",
    muscle_group: "Core",
    equipment: "Cables",
    image_url: "../../ejercicios/Cable Crunch - fondo blanco.png",
    target_muscles: ["Abdominales"],
    description: "Crunch arrodillado con cuerda en polea alta. Jala hacia abajo flexionando columna, llevando codos hacia rodillas. Tensión constante en abdominales. Uno de los mejores ejercicios para fuerza y desarrollo del recto abdominal.",
  },
  {
    id: "hanging_leg_raise",
    name: "Hanging Leg Raise",
    muscle_group: "Core",
    equipment: "Barra",
    image_url: "../../ejercicios/Hanging_Leg_Raise.png",
    target_muscles: ["Abdominales"],
    description: "Elevaciones de piernas colgado de barra. Levanta piernas controladamente hasta 90° o más. Trabaja abdominales inferiores intensamente. Evita balancear el cuerpo. Si es muy difícil, empieza con rodillas flexionadas.",
  },
  {
    id: "planks",
    name: "Plank",
    muscle_group: "Core",
    equipment: "Peso Corporal",
    image_url: "../../ejercicios/Plank.png",
    target_muscles: ["Core"],
    description: "Plancha isométrica para core completo. Mantén cuerpo recto como tabla desde cabeza hasta pies, apoyado en antebrazos y dedos. Trabaja recto abdominal, transverso, oblicuos y estabilizadores de espalda. Fundamental para fuerza del core y postura.",
  },

  // ===== CARDIO =====
  {
    id: "treadmill_running",
    name: "Running (Treadmill)",
    muscle_group: "Cardio",
    equipment: "Máquina",
    image_url: "../../ejercicios/Running_Treadmill.png",
    target_muscles: ["Piernas", "Cardiovascular"],
    description: "Carrera en caminadora. Excelente para salud cardiovascular y quema de calorías. Ajusta velocidad e inclinación según nivel. Intervalos de alta intensidad (HIIT) son muy efectivos. Calienta siempre antes de correr intenso.",
  },
  {
    id: "stationary_bike",
    name: "Stationary Bike",
    muscle_group: "Cardio",
    equipment: "Máquina",
    image_url: "../../ejercicios/Stationary_Bike.png",
    target_muscles: ["Piernas", "Cardiovascular"],
    description: "Bicicleta estática de bajo impacto. Ideal para cardio sin estrés articular. Trabaja cuádriceps, isquios y resistencia cardiovascular. Ajusta resistencia según objetivo. Perfecto para calentamiento, enfriamiento o sesión de cardio completa.",
  },
  {
    id: "jumping_jacks",
    name: "Jumping Jacks",
    muscle_group: "Cardio",
    equipment: "Peso Corporal",
    image_url: "../../ejercicios/Jumping_Jacks.png",
    target_muscles: ["Cuerpo Completo"],
    description: "Saltos de tijera, ejercicio cardiovascular clásico. Salta abriendo piernas y brazos, luego cierra. Calienta todo el cuerpo, aumenta ritmo cardíaco rápidamente. Ideal para calentamiento, circuitos o HIIT. Sin equipo necesario, hazlo donde sea.",
  },
];

export const MUSCLE_GROUPS = [
  "Pecho",
  "Espalda",
  "Hombros",
  "Brazos",
  "Piernas",
  "Glúteos",
  "Core",
  "Cardio",
];

export const EQUIPMENT_OPTIONS = [
  "Barra",
  "Mancuernas",
  "Cables",
  "Máquina",
  "Peso Corporal",
  "Smith Machine",
];
